create table "public"."user" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "uuid" uuid default auth.uid(),
    "email" character varying,
    "username" character varying,
    "status" text default 'active'::text,
    "role" text
);


CREATE UNIQUE INDEX us_pkey ON public."user" USING btree (id);

alter table "public"."user" add constraint "us_pkey" PRIMARY KEY using index "us_pkey";


