create table "public"."post_contact_history" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "post_uuid" uuid,
    "sender_uuid" uuid,
    "uuid" uuid default gen_random_uuid(),
    "message" character varying,
    "type" text
);


alter table "public"."post_contact_history" enable row level security;

create table "public"."referral_contact_history" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "uuid" uuid default gen_random_uuid(),
    "sender_uuid" uuid,
    "receiver_uuid" uuid,
    "type" text,
    "message" character varying
);


alter table "public"."referral_contact_history" enable row level security;

CREATE UNIQUE INDEX post_contact_history_id_key ON public.post_contact_history USING btree (id);

CREATE UNIQUE INDEX post_contact_history_pkey ON public.post_contact_history USING btree (id);

CREATE UNIQUE INDEX post_contact_history_uuid_key ON public.post_contact_history USING btree (uuid);

CREATE UNIQUE INDEX post_uuid_key ON public.post USING btree (uuid);

CREATE UNIQUE INDEX referral_contact_history_pkey ON public.referral_contact_history USING btree (id);

CREATE UNIQUE INDEX referral_contact_history_uuid_key ON public.referral_contact_history USING btree (uuid);

alter table "public"."post_contact_history" add constraint "post_contact_history_pkey" PRIMARY KEY using index "post_contact_history_pkey";

alter table "public"."referral_contact_history" add constraint "referral_contact_history_pkey" PRIMARY KEY using index "referral_contact_history_pkey";

alter table "public"."post" add constraint "post_uuid_key" UNIQUE using index "post_uuid_key";

alter table "public"."post_contact_history" add constraint "post_contact_history_id_key" UNIQUE using index "post_contact_history_id_key";

alter table "public"."post_contact_history" add constraint "post_contact_history_post_uuid_fkey" FOREIGN KEY (post_uuid) REFERENCES post(uuid) not valid;

alter table "public"."post_contact_history" validate constraint "post_contact_history_post_uuid_fkey";

alter table "public"."post_contact_history" add constraint "post_contact_history_sender_uuid_fkey" FOREIGN KEY (sender_uuid) REFERENCES "user"(uuid) not valid;

alter table "public"."post_contact_history" validate constraint "post_contact_history_sender_uuid_fkey";

alter table "public"."post_contact_history" add constraint "post_contact_history_uuid_key" UNIQUE using index "post_contact_history_uuid_key";

alter table "public"."referral_contact_history" add constraint "referral_contact_history_receiver_uuid_fkey" FOREIGN KEY (receiver_uuid) REFERENCES "user"(uuid) not valid;

alter table "public"."referral_contact_history" validate constraint "referral_contact_history_receiver_uuid_fkey";

alter table "public"."referral_contact_history" add constraint "referral_contact_history_sender_uuid_fkey" FOREIGN KEY (sender_uuid) REFERENCES "user"(uuid) not valid;

alter table "public"."referral_contact_history" validate constraint "referral_contact_history_sender_uuid_fkey";

alter table "public"."referral_contact_history" add constraint "referral_contact_history_uuid_key" UNIQUE using index "referral_contact_history_uuid_key";

create policy "Enable insert for authenticated users only"
on "public"."post_contact_history"
as permissive
for insert
to authenticated
with check (true);


create policy "Enable insert for authenticated users only"
on "public"."referral_contact_history"
as permissive
for insert
to authenticated
with check (true);



