alter table "public"."email_notification_log" drop constraint "email_notification_log_user_uuid_fkey";

alter table "public"."email_notification_log" drop column "sent_at";

alter table "public"."email_notification_log" add column "created_at" timestamp with time zone default now();

alter table "public"."email_notification_log" alter column "body" drop not null;

alter table "public"."email_notification_log" alter column "email" set data type character varying(255) using "email"::character varying(255);

alter table "public"."email_notification_log" alter column "id" drop default;

alter table "public"."email_notification_log" alter column "id" add generated by default as identity;

alter table "public"."email_notification_log" alter column "id" set data type integer using "id"::integer;

alter table "public"."email_notification_log" alter column "title" drop not null;

alter table "public"."email_notification_log" alter column "title" set data type text using "title"::text;

create policy "Enable insert for authenticated users only"
on "public"."message_notification_queue"
as permissive
for insert
to authenticated
with check (true);



