ALTER TABLE "public"."email_notification_log" DROP CONSTRAINT IF EXISTS "email_notification_log_user_uuid_fkey";

ALTER TABLE "public"."email_notification_log" DROP COLUMN IF EXISTS "sent_at";

ALTER TABLE "public"."email_notification_log" ADD COLUMN IF NOT EXISTS "created_at" timestamp with time zone DEFAULT now();

ALTER TABLE "public"."email_notification_log" ALTER COLUMN "body" DROP NOT NULL;

ALTER TABLE "public"."email_notification_log" ALTER COLUMN "email" SET DATA TYPE character varying(255) USING "email"::character varying(255);

-- Change the order here
ALTER TABLE "public"."email_notification_log" ALTER COLUMN "id" SET DATA TYPE integer USING "id"::integer;
ALTER TABLE "public"."email_notification_log" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "public"."email_notification_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "public"."email_notification_log" ALTER COLUMN "title" DROP NOT NULL;

ALTER TABLE "public"."email_notification_log" ALTER COLUMN "title" SET DATA TYPE text USING "title"::text;

CREATE POLICY IF NOT EXISTS "Enable insert for authenticated users only"
ON "public"."message_notification_queue"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);
