-- Step 1: Drop the existing email_notification_log table if it exists
DROP TABLE IF EXISTS "public"."email_notification_log";

-- Step 2: Create the email_notification_log table again
CREATE TABLE "public"."email_notification_log" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_uuid" uuid NOT NULL,
    "email" character varying(255),
    "body" text,
    "title" text,
    "created_at" timestamp with time zone DEFAULT now()
);

-- Step 3: Create a policy for message_notification_queue
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON "public"."message_notification_queue";

CREATE POLICY "Enable insert for authenticated users only"
ON "public"."message_notification_queue"
AS PERMISSIVE
FOR INSERT
TO authenticated
WITH CHECK (true);
