create sequence "public"."email_notification_log_id_seq";

alter table "public"."email_notification_log" alter column "id" drop default;

alter table "public"."email_notification_log" alter column "id" add generated by default as identity;

alter table "public"."email_notification_log" alter column "id" set data type bigint using "id"::bigint;

alter sequence "public"."email_notification_log_id_seq" owned by "public"."email_notification_log"."id";

CREATE UNIQUE INDEX email_notification_log_id_key ON public.email_notification_log USING btree (id);

alter table "public"."email_notification_log" add constraint "email_notification_log_id_key" UNIQUE using index "email_notification_log_id_key";

create policy "Enable insert for authenticated users only"
on "public"."message_notification_queue"
as permissive
for insert
to authenticated
with check (true);



