revoke delete on table "public"."notification" from "authenticated";

revoke insert on table "public"."notification" from "authenticated";

revoke references on table "public"."notification" from "authenticated";

revoke trigger on table "public"."notification" from "authenticated";

revoke truncate on table "public"."notification" from "authenticated";

revoke update on table "public"."notification" from "authenticated";

create table "public"."fire" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" text not null,
    "ref_uuid" uuid not null,
    "created_by" uuid not null default auth.uid()
);


alter table "public"."fire" enable row level security;

CREATE INDEX fire_created_by_idx ON public.fire USING btree (created_by);

CREATE UNIQUE INDEX fire_pkey ON public.fire USING btree (id);

CREATE UNIQUE INDEX fire_ref_uuid_created_by_unique ON public.fire USING btree (ref_uuid, created_by);

alter table "public"."fire" add constraint "fire_pkey" PRIMARY KEY using index "fire_pkey";

alter table "public"."fire" add constraint "fire_ref_uuid_created_by_unique" UNIQUE using index "fire_ref_uuid_created_by_unique";

alter table "public"."fire" add constraint "fire_type_check" CHECK ((type = 'job_journey'::text)) not valid;

alter table "public"."fire" validate constraint "fire_type_check";

alter table "public"."fire" add constraint "public_fire_created_by_fkey" FOREIGN KEY (created_by) REFERENCES "user"(uuid) not valid;

alter table "public"."fire" validate constraint "public_fire_created_by_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.increment_job_journey_fire_count()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
    IF NEW.type = 'job_journey' THEN
        UPDATE public.job_journey
        SET fire_count = fire_count + 1
        WHERE uuid = NEW.ref_uuid;
        
        IF NOT FOUND THEN
            RAISE NOTICE 'No job_journey found for ref_uuid: %', NEW.ref_uuid;
        END IF;
    END IF;
    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.notify_on_message_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$DECLARE
    notification_user_uuid UUID;
    sender_username_val TEXT;
    has_document_val BOOLEAN;
BEGIN
    -- Get the recipient user UUID and message details
    SELECT 
        CASE 
            WHEN NEW.sender_uuid = c.sender_uuid THEN c.receiver_uuid 
            ELSE c.sender_uuid 
        END,
        u.username
    INTO notification_user_uuid, sender_username_val
    FROM conversation c
    JOIN public.user u ON NEW.sender_uuid = u.uuid  -- Assuming users table has uuid and username
    WHERE c.uuid = NEW.conversation_uuid;

    -- Check if document is not null
    has_document_val := NEW.document IS NOT NULL;

    -- Insert into the notification table directly
    INSERT INTO notification (
        user_uuid,
        type,
        data,
        created_at,
        is_seen
    ) VALUES (
        notification_user_uuid,
        'message',  -- Hardcoded notification type
        jsonb_build_object(
            'sender_username', "sender_username_val",
            'has_document', has_document_val,
            'conversation_uuid', "NEW.conversation_uuid",
            'message_uuid', "NEW.uuid"  -- Add the message UUID
        ),
        NEW.created_at,
        FALSE
    );

    RETURN NEW;
END;$function$
;

grant delete on table "public"."fire" to "anon";

grant insert on table "public"."fire" to "anon";

grant references on table "public"."fire" to "anon";

grant select on table "public"."fire" to "anon";

grant trigger on table "public"."fire" to "anon";

grant truncate on table "public"."fire" to "anon";

grant update on table "public"."fire" to "anon";

grant delete on table "public"."fire" to "authenticated";

grant insert on table "public"."fire" to "authenticated";

grant references on table "public"."fire" to "authenticated";

grant select on table "public"."fire" to "authenticated";

grant trigger on table "public"."fire" to "authenticated";

grant truncate on table "public"."fire" to "authenticated";

grant update on table "public"."fire" to "authenticated";

grant delete on table "public"."fire" to "service_role";

grant insert on table "public"."fire" to "service_role";

grant references on table "public"."fire" to "service_role";

grant select on table "public"."fire" to "service_role";

grant trigger on table "public"."fire" to "service_role";

grant truncate on table "public"."fire" to "service_role";

grant update on table "public"."fire" to "service_role";

create policy "created own fire"
on "public"."fire"
as permissive
for insert
to authenticated
with check ((created_by = auth.uid()));


create policy "select own fires"
on "public"."fire"
as permissive
for select
to authenticated
using ((created_by = auth.uid()));


CREATE TRIGGER fire_job_journey_trigger AFTER INSERT ON public.fire FOR EACH ROW EXECUTE FUNCTION increment_job_journey_fire_count();


